server:
  port: 8082
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${db_url}:5432/postgres
    username: ${db_user}
    password: ${db_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  jackson:
    serialization:
      fail-on-empty-beans: false
feign:
  hystrix:
    enabled: true
    
