server:
  port: 8082
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${PostgresURL}:5432/postgres
    username: postgres
    password: ${PostgresPW}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
feign:
  hystrix:
    enabled: true